name: CompatHelper
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      # - uses: JuliaRegistries/compathelper-action@v1 # TODO: uncomment this line
      - uses: JuliaRegistries/compathelper-action@main # TODO: delete this line
        with:
          ssh: ${{ secrets.DOCUMENTER_KEY }}
